### ISSUE TITLE
URL routing bug

### ISSUE THREAD

**Issue by Kevinwochan** [ocius/website#30]
when trying to access some blog posts, the page loads but then users are redirected to an invalid URL e.g

https://ocius.com.au/blog/7863/ is redirected to https://blog/7863//

https://ocius.com.au/blog/ocius-successfully-completes-seatrials is redirected to https://blog/ocius-successfully-completes-seatrials//
https://ocius.com.au/blog/ocius-successfully-completes-seatrials/ (with the '/' works)

https://ocius.com.au/blog/abc-news-navy-explores-use-of-autonomous-vehicles-for-dangerous-dirty-and-dull-work/

**Comment by r007** [comment]
I think I've seen somewhere a similar issue, don't remember where. This project was configured to use trailing slashes:
```js
// Create the Gatsby page for this WordPress post
createPage({
  path: `/${post.fields.slug}/`,
  component: postTemplate,
  context: {
    // Data passed to context is available
    // in page queries as GraphQL variables.
    slug: post.fields.slug
  }
});
```
But we can simply use ```path: post.fields.slug``` instead of

```js
path: `/${post.fields.slug}/`
```
I fixed it. @thomasdane, can you accept my pull request and then @Kevinwochan can you check if issue resolved or not? Thanks.

**Comment by thomasdane** [comment]
The PR to fix this is merged https://github.com/ocius/website/pull/33 @Kevinwochan please let me know if it's not resolved.

**Comment by Kevinwochan** [comment]
:cry: still doesn't seem to work
Interestingly, the URLs work on localhost e.g http://localhost:8000/blog/ocius-successfully-completes-seatrials .

Could this be an server side issue rather than a gatsby issue?

**Comment by r007** [comment]
Kevin, yeah you're right. The URL routing bug has been fixed on localhost, but I still see it on production website. Interestingly enough, some URLs work fine, for example:
https://ocius.com.au/blog/prototype-bob-begins-sea-trials-off-nsw-coast
https://ocius.com.au/blog/ocius-demonstrates-man-portable-usv-prototype-at-aw18
https://ocius.com.au/blog/defence-connect-ocius-technology-awarded-defence-innovation-hub-contract

It might have something to do with:

a) Caching/Presence of the old data. Try to do ```gatsby clean``` and then ```gatsby build```. Clear browser cache.
b) AWS setup. Need to ask @thomasdane to check whether Amazon caches the data. Also, it might be some kind of sneaky redirect rules.
c) Offline support. I also suspect that workers can cache the old data.

On localhost everything works well.

**Comment by r007** [comment]
This problem seems be solved when we moved from AWS S3 -> AWS Amplify. Check this out:

https://live-page.d3mmixckvnis5d.amplifyapp.com/blog/7863
https://live-page.d3mmixckvnis5d.amplifyapp.com/blog/ocius-successfully-completes-seatrials
https://live-page.d3mmixckvnis5d.amplifyapp.com/blog/ocius-begins-intelligent-network-trials

Turns out to be hosting issue.

**Comment by Kevinwochan** [comment]
Are all production servers now on AWS Amplify now?
Some of the team is still having issues with certain links
E.g 
https://ocius.com.au/blog/abc-news-navy-explores-use-of-autonomous-vehicles-for-dangerous-dirty-and-dull-work/

https://ocius.com.au/blog/ocius-demonstrates-man-portable-usv-prototype-at-aw18/

**Comment by r007** [comment]
Not yet. Ocius.com.au is not on Amplify yet. We migrated only https://www.ocius.cloud/ to AWS Amplify.

By the way, @Kevinwochan can you please always add ```featuredImage``` to blog posts, no matter what? It doesn't look too good on home page. Plus, PropTypes are throwing error if featured image is missing.

![Home page](https://user-images.githubusercontent.com/78280/66255371-b2f32a00-e793-11e9-879c-9dbc1758e342.png)

**Comment by thomasdane** [comment]
@r007 @Kevinwochan ocius.com.au is now on amplify. All our URLs are deployed with amplify now.

**Comment by r007** [comment]
Checked again, everything seems to be working fine. I'm closing this issue, feel free to re-open if needed.
